remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: FOSS4G 2025 â€” Fast, Free, and (Mostly) Painless - Open-Source Web Mapping Examples
description: FOSS4G 2025
show_downloads: true
